### ISSUE TITLE
Add an entrypoint script that restarts Invidious every Xh

### ISSUE THREAD

**Issue by mcmikemn** [EnigmaCurry/d.rymcg.tech#358]
Invidious suggests "because of various issues Invidious must be restarted often, at least once a day, ideally every hour." 

It might be nice to incorporate automatic periodic restarting of Invidious as an entrypoint script, perhaps where the period between restarts is defined in `INVIDIOUS_RESTART_FREQUENCY=24h`

**Comment by EnigmaCurry** [comment]
I think a healthcheck could work even easier than an entrypoint:

```
services:
  invidious:
    image: ...
    healthcheck:
      test: ["CMD", "exit 1"]
      interval: ${INVIDIOUS_RESTART_FREQUENCY}
      timeout: 10s
      start_period: 10s
      retries: 0
```
