### ISSUE TITLE
Add plugins to redmine

### ISSUE THREAD

**Issue by mcmikemn** [EnigmaCurry/d.rymcg.tech#440]
Add plugin functionality to Redmine, include Gantt plugin. (https://www.easyredmine.com/redmine-gantt-plugin).

ChatGPT suggestion:

Folder Structure
```
redmine-docker/
├── docker-compose.yml
├── Dockerfile
└── plugins/
    └── redmine_example_plugin/   # Cloned plugin repo
```
Dockerfile
```
FROM redmine:6.0

# Copy plugins into image
COPY plugins /usr/src/redmine/plugins

# Install dependencies and migrate
WORKDIR /usr/src/redmine
RUN bundle install && \
    bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```

docker-compose.yml
```
services:
  redmine:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - redmine_data:/usr/src/redmine/files
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: secret
      REDMINE_DB_ENCODING: utf8

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  redmine_data:
  mysql_data:
```
